apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: {{ .Values.MyName }}/{{ .Values.AppName.Main }}:8ac9a55
        env:
        - name: DEFAULT_DB_URL
          value: "192.168.99.2"
        ports:
        - containerPort: 8080
      {{ if eq .Values.Env "stg" }}
      - name: cloud-sql
        image: {{ .Values.MyName }}/{{ .Values.AppName.CloudSql }}:0.1
        ports:
        - containerPort: 3306
      {{ end }}