apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: {{ .Values.Apps.Main.Image }}
        env:
        - name: DEFAULT_DB_URL
          value: {{ .Values.Apps.Main.Env.DefaultDBUrl }}
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
      {{ if eq .Values.Env "stg" }}
      - name: cloud-sql
        image: {{ .Values.Apps.CloudSql.Image }}
        env:
        - name: CLOUD_SQL_INSTANCE
          value: {{ .Values.Apps.CloudSql.Env.CloudSqlInstance }}
        ports:
        - containerPort: 3306
      {{ end }}
      volumes:
      - name: config
        secret:
          secretName: {{ .Release.Name }}-secret