{{ if eq .Values.Env "stg" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.Ingress.StaticIpName }}
spec:
  backend:
    serviceName: {{ .Release.Name }}-service
    servicePort: 80
{{ end }}