apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
data:
  {{- $files := .Files }}
  {{- range tuple "config1.toml" "config2.toml" }}
  {{ . }}: |-
    {{ $files.Get . | b64enc }}
  {{- end }}